// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDr4fquRMB3sRrNYodpuYLIzjaedA0ctso',
    appId: '1:121093403449:web:6730ba031a7149a63a6ee8',
    messagingSenderId: '121093403449',
    projectId: 'maps-app2-f574f',
    authDomain: 'maps-app2-f574f.firebaseapp.com',
    storageBucket: 'maps-app2-f574f.appspot.com',
    measurementId: 'G-574HSKJXZY',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBdOLnNNzz8gsvgy4DSnGPLn1DPjHiwF50',
    appId: '1:121093403449:android:6b7da591133614e93a6ee8',
    messagingSenderId: '121093403449',
    projectId: 'maps-app2-f574f',
    storageBucket: 'maps-app2-f574f.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAD758Q-ke-r9zh3n8rj1Rp0pTKwrvQ5hM',
    appId: '1:121093403449:ios:9c8ea6a79bbcb49b3a6ee8',
    messagingSenderId: '121093403449',
    projectId: 'maps-app2-f574f',
    storageBucket: 'maps-app2-f574f.appspot.com',
    iosBundleId: 'com.example.mapsApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAD758Q-ke-r9zh3n8rj1Rp0pTKwrvQ5hM',
    appId: '1:121093403449:ios:9c8ea6a79bbcb49b3a6ee8',
    messagingSenderId: '121093403449',
    projectId: 'maps-app2-f574f',
    storageBucket: 'maps-app2-f574f.appspot.com',
    iosBundleId: 'com.example.mapsApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDr4fquRMB3sRrNYodpuYLIzjaedA0ctso',
    appId: '1:121093403449:web:128e401c47debf773a6ee8',
    messagingSenderId: '121093403449',
    projectId: 'maps-app2-f574f',
    authDomain: 'maps-app2-f574f.firebaseapp.com',
    storageBucket: 'maps-app2-f574f.appspot.com',
    measurementId: 'G-S9W075T8B5',
  );

}